name: deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: uenot/tobyuenodotcom
          ref: main

      - name: node-download
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: ci
        run: npm ci

      - name: build
        run: npm run build

      - name: pages-setup
        uses: actions/configure-pages@v5

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: pages-deploy
        id: deployment
        uses: actions/deploy-pages@v4
