name: deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: uenot/tobyuenodotcom
          ref: dev
            
      - name: build
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - run: elm make src/Main.elm

      - name: pages-setup
        uses: actions/configure-pages@v3

      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
          
      - name: pages-deploy
        id: deployment
        uses: actions/deploy-pages@v2
